import type { ExtensionHost, KnowledgeItem, MediaAsset } from '@neo-anki/extension-sdk'
import { dataUrl, synthesizeWithFallback } from './providers.js'
import { metadataKey, readTtsMetadata, type AttachAudioPayload } from './media.js'
import { stableHash, textForTrack } from './text.js'
import type { ProviderConfig, TtsProfile, TtsTrack } from './types.js'

export const cacheKeyFor = (track: TtsTrack, text: string, providers: ProviderConfig) => stableHash(JSON.stringify({
  text, provider: track.provider, voice: track.voice, language: track.language, model: track.model,
  speed: track.speed, instructions: track.instructions, defaults: providers,
  voiceMode: track.voiceMode, fallbacks: track.fallbacks,
}))

export const isCurrent = async (item: KnowledgeItem, profile: TtsProfile, track: TtsTrack, providers: ProviderConfig) => {
  const text = textForTrack(track, item, profile.processing)
  if (!text) return true
  const current = readTtsMetadata(item).tracks[metadataKey(profile.id, track.id)]
  return Boolean(current && current.cacheKey === await cacheKeyFor(track, text, providers))
}

const bytesFromBase64 = (value: string) => Math.max(0, Math.floor(value.length * 3 / 4) - (value.endsWith('==') ? 2 : value.endsWith('=') ? 1 : 0))
const wait = (milliseconds: number) => new Promise((resolve) => window.setTimeout(resolve, milliseconds))

export const generateTrackPayload = async ({
  item, profile, track, providers, host, retries, shouldStop = () => false,
}: {
  item: KnowledgeItem
  profile: TtsProfile
  track: TtsTrack
  providers: ProviderConfig
  host: ExtensionHost
  retries: number
  shouldStop?: () => boolean
}): Promise<AttachAudioPayload | null> => {
  const text = textForTrack(track, item, profile.processing)
  if (!text) return null
  const cacheKey = await cacheKeyFor(track, text, providers)
  let attempt = 0
  while (true) {
    if (shouldStop()) throw new Error('Generation stopped.')
    try {
      const result = await synthesizeWithFallback(host, track, text, providers)
      const audioHash = await stableHash(result.audioBase64)
      const timestamp = new Date().toISOString()
      const asset: MediaAsset = {
        id: `tts-${audioHash}`, filename: `neoanki-tts-${profile.id}-${track.id}-${audioHash.slice(0, 12)}.${result.extension}`,
        mimeType: result.mimeType, dataUrl: dataUrl(result), byteLength: bytesFromBase64(result.audioBase64), hash: audioHash,
        altText: `${track.name} audio generated by ${track.provider}`, createdAt: timestamp, updatedAt: timestamp,
      }
      return {
        itemId: item.id,
        asset,
        metadata: { profileId: profile.id, trackId: track.id, assetId: asset.id, cacheKey, generatedAt: timestamp, side: track.side, provider: track.provider },
      }
    } catch (error) {
      if (attempt >= retries || shouldStop()) throw error
      attempt += 1
      await wait(300 * 2 ** (attempt - 1))
    }
  }
}
