export const TtsStyles = () => <style>{`
  .tts-shell{display:grid;gap:18px;padding:18px;border:1px solid var(--border);border-radius:14px;background:var(--surface-strong);color:var(--text)}
  .tts-head{display:flex;justify-content:space-between;align-items:flex-start;gap:16px}.tts-head h2{margin:0 0 5px;font-size:1.05rem}.tts-head p{margin:0;color:var(--text-soft);font-size:.8rem;line-height:1.5;max-width:68ch}
  .tts-tabs{display:flex;gap:4px;padding:4px;background:var(--surface);border:1px solid var(--border);border-radius:10px;overflow:auto}.tts-tab{min-height:40px;padding:0 13px;border:0;border-radius:7px;background:transparent;color:var(--text-soft);font:inherit;font-size:.76rem;font-weight:750;cursor:pointer;white-space:nowrap}.tts-tab[aria-selected=true]{background:var(--surface-strong);color:var(--text);box-shadow:0 1px 4px rgba(0,0,0,.08)}
  .tts-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.tts-grid.three{grid-template-columns:repeat(3,minmax(0,1fr))}.tts-card{padding:15px;border:1px solid var(--border);border-radius:11px;background:var(--surface)}.tts-card h3{margin:0 0 5px;font-size:.85rem}.tts-card p{margin:0;color:var(--text-soft);font-size:.74rem;line-height:1.5}
  .tts-field{display:grid;gap:6px;color:var(--text-soft);font-size:.7rem;font-weight:750}.tts-field input,.tts-field select,.tts-field textarea{width:100%;min-height:44px;box-sizing:border-box;padding:9px 10px;border:1px solid var(--border-strong);border-radius:8px;background:var(--surface-strong);color:var(--text);font:inherit}.tts-field textarea{min-height:76px;resize:vertical}.tts-field input:focus,.tts-field select:focus,.tts-field textarea:focus{outline:3px solid color-mix(in srgb,var(--accent) 24%,transparent);border-color:var(--accent)}
  .tts-row{display:flex;align-items:center;gap:9px;flex-wrap:wrap}.tts-between{display:flex;align-items:center;justify-content:space-between;gap:12px}.tts-check{display:flex;align-items:center;gap:9px;min-height:44px;color:var(--text);font-size:.76rem;font-weight:650}.tts-check input{width:17px;height:17px}
  .tts-button{min-height:44px;padding:0 14px;border:1px solid var(--border-strong);border-radius:8px;background:var(--surface-strong);color:var(--text);font:inherit;font-size:.74rem;font-weight:750;cursor:pointer}.tts-button:hover{border-color:var(--accent)}.tts-button.primary{background:var(--accent);border-color:var(--accent);color:white}.tts-button.danger{color:var(--danger)}.tts-button:disabled{opacity:.48;cursor:not-allowed}
  .tts-track{display:grid;gap:13px;padding:15px;border:1px solid var(--border);border-radius:11px;background:var(--surface)}.tts-track-head{display:flex;align-items:center;justify-content:space-between;gap:10px}.tts-track-head strong{font-size:.8rem}.tts-muted{color:var(--text-soft);font-size:.72rem;line-height:1.5}.tts-status{min-height:20px;margin:0;color:var(--text-soft);font-size:.73rem}.tts-status[role=alert]{color:var(--danger)}
  .tts-progress{height:8px;background:var(--border);border-radius:999px;overflow:hidden}.tts-progress span{display:block;height:100%;background:var(--accent);transition:width 180ms ease-out}.tts-log{max-height:180px;overflow:auto;margin:0;padding:10px 10px 10px 28px;border:1px solid var(--border);border-radius:8px;color:var(--text-soft);font-size:.7rem;line-height:1.6}
  .tts-provider-state{display:inline-flex;align-items:center;gap:6px;font-size:.68rem;font-weight:750;color:var(--text-soft)}.tts-dot{width:8px;height:8px;border-radius:50%;background:var(--border-strong)}.tts-dot.on{background:#218a54}.tts-divider{height:1px;background:var(--border);margin:3px 0}
  @media(max-width:760px){.tts-grid,.tts-grid.three{grid-template-columns:1fr}.tts-head{flex-direction:column}.tts-between{align-items:flex-start;flex-direction:column}}
  @media(prefers-reduced-motion:reduce){.tts-progress span{transition:none}}
`}</style>
